apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-seed
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-seed
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 75