apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ms-seed
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-seed
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 75